# Основные настройки
title: Константин
description: Ваш блог
baseurl: ""
url: "https://samaren.github.io"
theme: minima

# Настройки блога
collections:
  posts:
    output: true
    permalink: /:year/:title/

# Плагины
plugins:
  - jekyll-feed
  - jekyll-paginate

# Навигация
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      repository: Samaren/Samaren.github.io
      plugins:
  - jekyll-feed
  - jekyll-seo-tag
