name: Jekyll site CI

on:
  push:
    branches: ["main"] # или "master" если используете старую ветку

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Совместимая версия с GitHub Pages
          bundler-cache: true
          
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v2
        with:
          source: ./
          destination: ./_site
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
